#!/bin/bash

instruments=( "Kurbel" "kuehler" "theremin" "trichter" "eieiei" "goldenbox" "bassfahrer" "foen" "bank")
CMD="$1"


for i in "${instruments[@]}"
do
	if [ -z "$CMD" ]
	then
		screen -t $i
		screen -p $i -X stuff "ssh pi@$i\n"
	else
		screen -p $i -X stuff "$CMD"
	fi
done
