#!/bin/bash

instruments=( "Kurbel" "kuehler" "theremin" "trichter" "eieiei" "goldenbox" "bassfahrer" "foen")



for i in "${instruments[@]}"
do
	echo -e "\e[31mrun cmd on Instrument $i: "
	echo -e "\e[0m"
	ssh pi@$i $1
done
